name: teste_tecnico01_escribo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
